import Universality.Percolation.InternalMassPaperNormalization
import Universality.Percolation.InternalMassPointTail
import Universality.Graph.UniformRootLocalLimit
import Universality.Graph.UniformRootCriticalFiniteness
import Universality.Graph.PhysicalRadiusExponents
import Universality.Percolation.PhysicalMomentExponents
import Universality.Percolation.ActualMomentPowerBounds
import Universality.Percolation.ActualRootMomentContinuity
import Universality.Percolation.PhysicalClusterNumberAnalyticity
import Universality.Examples.PhysicalRawAlphaExamples
import Universality.Percolation.GeometricPhysicalClass
import Universality.Percolation.CyclicPhysicalClass
import Universality.Examples.DiamondFourPhysicalExponents
import Universality.Examples.TieGemPhysicalClass
import Universality.Examples.TieGemResistance
import Universality.Examples.TieGemCommonSpectrum
import Universality.Examples.TieGemResponseBounds
import Universality.Examples.DiamondSusceptibilityNumerical
import Universality.Examples.WheatstoneAlphaNumerical
import Universality.Graph.ResistanceObservation

/-! The original manuscript Section 3, including the four additional exponents
later moved to an appendix. The individual declarations retain their explicit
geometric and probabilistic hypotheses. -/
