import Universality.Arithmetic.Section4Complete
import Universality.Geometry.CellHausdorffUpperBound
import Section4KernelAudit

/-! Combined audit of every imported project declaration. The geometric and
physical interfaces retain the precise observable and geometric meanings. -/

#audit_section4_axioms

#print axioms Universality.Rule.generationMetricSpace_dimH_eq
#print axioms Universality.Rule.Classical.criticalDimensions_geometric_finite_growth
#print axioms Universality.Rule.CoreObservableExponents.to_formula
#print axioms Universality.Rule.Classical.existsUnique_coreObservableExponents
#print axioms Universality.Rule.CoreObservableExponents.positive
#print axioms Universality.Rule.Classical.coreObservableExponents_eq_iff_criticalDimensions_eq
#print axioms Universality.Rule.Classical.commensurate_of_coreObservableExponents_rank
#print axioms Universality.Rule.Classical.commensurate_of_coreObservableExponents_irreducible
#print axioms Universality.Rule.Classical.common_primitive_base_of_coreObservableExponents_rank
#print axioms Universality.Rule.Classical.common_primitive_base_of_coreObservableExponents_irreducible
#print axioms Universality.Rule.Classical.scale_log_rank_le_two_of_coreObservableExponents
#print axioms Universality.Rule.Classical.aligned_coreObservableExponents_iff
#print axioms Universality.Rule.Classical.scale_power_two_of_wheatstone_coreObservableExponents
#print axioms Universality.Rule.Classical.scale_power_two_of_diamond_coreObservableExponents
#print axioms Universality.Rule.Classical.massPlane_charpoly_irreducible_iff

#print axioms Universality.Rule.Classical.same_physical_class_iff_criticalDimensions
#print axioms Universality.Rule.Classical.commensurate_of_physicalClass_rank
#print axioms Universality.Rule.Classical.criticalDimension_rank_le_two_of_physicalClass_not_commensurate
#print axioms Universality.Rule.Classical.commensurate_of_physicalClass_irreducible
#print axioms Universality.Rule.Classical.common_primitive_base_of_physicalClass_rank
#print axioms Universality.Rule.Classical.common_primitive_base_of_physicalClass_irreducible
#print axioms Universality.Rule.Classical.scale_log_rank_le_two_of_physicalClass
#print axioms Universality.Rule.Classical.aligned_physicalClass_iff
#print axioms Universality.Rule.Classical.scale_power_two_of_wheatstone_physicalClass
#print axioms Universality.Rule.Classical.scale_power_two_of_diamond_physicalClass
