import Universality.Section5.PhysicalExponents

#print axioms Universality.Rule.uniformRootInfiniteClusterEvent_iff
#print axioms Universality.Rule.generation_uniformRootSample_size_tendsto
#print axioms Universality.Rule.uniformRootFiniteClusterProbability_eq_limiting
#print axioms Universality.Rule.uniformRootInfiniteClusterProbability_eq_escapingRootMass
#print axioms Universality.Rule.physicalInfiniteClusterProbability_eq
#print axioms Universality.Rule.physicalFiniteClusterProbability_eq
#print axioms Universality.Rule.Classical.physical_beta_exponent
#print axioms Universality.Rule.Classical.physical_delta_exponent
#print axioms Universality.Rule.Classical.crossing_length_exponent
#print axioms Universality.Rule.Classical.averaged_connectivity_exponent
#print axioms Universality.Rule.Classical.hasCriticalExponents
#print axioms Universality.Rule.critical_exponents_unique
#print axioms Universality.Rule.Classical.hasCriticalExponents_in_dimensions
#print axioms Universality.Rule.Classical.same_critical_exponent_class_iff_dimensions
#print axioms Universality.Section5.RuleResponses.interior_nonempty
#print axioms Universality.Section5.RuleResponses.edges_neZero
#print axioms Universality.Section5.RuleResponses.hasCriticalExponents
#print axioms Universality.Section5.RuleResponses.physical_infinite_cluster_positive_iff
#print axioms Universality.Section5.RuleResponses.sameCriticalExponentUniversalityClass
#print axioms Universality.Section5.ExactAllocationCertificate.interior_nonempty
#print axioms Universality.Section5.ExactAllocationCertificate.edges_neZero
#print axioms Universality.Section5.ExactAllocationCertificate.physical_infinite_cluster_positive_iff
