from pathlib import Path
import json
r=Path('.')
namesA=['RadiusBlockProbability','GeometricTailDifferences','RadiusPointExponentUpper','RadiusPointExponentLower','RadiusPointExponent','RadiusPointNonexistence']
namesP=['CriticalRadiusPointExponent','CriticalRadiusPointValue','RadiusPointCounts','RadiusPointTransfer','RadiusPointEquivalence','PhysicalObservables','PhysicalCriticalExponents','PhysicalExponentDefinition','PhysicalExponentDimensions','PhysicalExponentClass']
mapping={**{'scratch.'+n:'Universality.Analysis.'+n for n in namesA},**{'scratch.'+n:'Universality.Percolation.'+n for n in namesP}}
replacement={**mapping,'scratch.UniformRootGraph.UniformRootSizeIdentification':'Universality.Graph.UniformRootSizeIdentification','scratch.AveragedConnectivityExponent':'Universality.Percolation.AveragedConnectivityExponent'}
for source,target in mapping.items():
 t=(r/(source.replace('.','/')+'.lean')).read_text(encoding='utf-8-sig')
 for old,new in sorted(replacement.items(),key=lambda kv:-len(kv[0])): t=t.replace('import '+old+'\n','import '+new+'\n')
 assert 'import scratch.' not in t, source
 (r/(target.replace('.','/')+'.lean')).write_text(t,encoding='utf-8')
extra=['Universality.Graph.FiniteAgeDisintegration','Universality.Graph.FiniteAgeBounds','Universality.Graph.UniformRootSizeIdentification','Universality.Analysis.StoppedMomentLogRate','Universality.Percolation.NearCriticalMomentLogRate','Universality.Percolation.ActualMomentLogRate','Universality.Percolation.MomentRatioLogRate']
audits=['Universality.'+n for n in ['exists_small_point_in_block','dyadic_window_log_growth','geometric_tail_bound_of_differences','point_log_limit_le_of_dyadic_block_bound','point_log_limit_ge_of_geometric_tail','point_log_limit_eq_of_tail_power_bounds','no_point_log_limit_of_dyadic_spikes','Rule.Classical.critical_radius_point_exponent_if_exists','Rule.Classical.critical_radius_point_exponent_value','FiniteNetwork.clusterRadiusRootCount_eq_point_add','FiniteNetwork.expectedInternalRadiusPointRootCount_eq_difference','Rule.Classical.internal_radius_point_partial_sum_le_limit','Rule.Classical.internal_radius_point_expectation_le_limit','FiniteNetwork.NetworkEquivalence.internalRadiusPointRootCount','FiniteNetwork.NetworkEquivalence.expectedInternalRadiusPointRootCount','Rule.physicalInfiniteClusterProbability_eq','Rule.physicalFiniteClusterProbability_eq','Rule.physicalFiniteClusterMoment_eq','Rule.Classical.physical_infinite_cluster_positive_iff','Rule.Classical.physical_beta_exponent','Rule.Classical.physical_delta_exponent','Rule.Classical.hasCriticalExponents','Rule.critical_exponents_unique','Rule.Classical.hasCriticalExponents_in_dimensions','Rule.Classical.same_critical_exponent_class_iff_dimensions','Rule.uniformVertexClusterProbability_by_age','Rule.weightedAncestralStageClusterProbability','Rule.finiteRootAgeProbability_le_geometric','Rule.terminalRootClusterContribution_tendsto_zero','Rule.generation_uniformRootSample_size_tendsto','Rule.uniformRootFiniteClusterProbability_eq_limiting','Rule.uniformRootInfiniteClusterProbability_eq_escapingRootMass','stopped_geometric_comparison_log_rate','stopped_moment_logarithmic_exponent','Rule.Classical.root_moment_log_rate_from_capped_comparison','Rule.Classical.supercritical_root_moment_log_rate','Rule.Classical.subcritical_root_moment_log_rate','logarithmic_ratio_from_log_rates','Rule.Classical.supercritical_root_moment_ratio_log_rate','Rule.Classical.subcritical_root_moment_ratio_log_rate']]
for filename,items,prefix in [('Universality.lean',list(mapping.values())+extra,'import '),('Audit.lean',audits,'#print axioms ')]:
 p=r/filename;t=p.read_text(encoding='utf-8-sig');old=set(t.splitlines());t=t.rstrip()+'\n'+''.join(prefix+x+'\n' for x in items if prefix+x not in old);p.write_text(t,encoding='utf-8')
(r/'scripts/section3_seventh_root_migration.json').write_text(json.dumps({'root_mapping':mapping,'additional_modules':extra,'audits':audits},indent=2)+'\n',encoding='utf-8')
print({'root_verified_candidates_migrated':len(mapping),'additional_agent_candidates':len(extra),'audit_additions':len(audits)})
