from pathlib import Path
import json
r=Path('.')
s=json.loads((r/'SECTION3_CONTINUATION_STATE.json').read_text(encoding='utf-8-sig'))
s['last_archive_updated_utc']='2026-10-06T17:34:36.229Z';s['last_project_index_updated_utc']='2026-10-06T17:36:35.464Z'
(r/'SECTION3_CONTINUATION_STATE.json').write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
modules=['Universality.Analysis.GeometricSumLogRate','Universality.Analysis.StoppedGeometricPowerBounds','Universality.Percolation.MomentExitTendsto','Universality.Percolation.NearCriticalMomentPowerBounds','Universality.Percolation.ActualMomentPowerBounds','Universality.Analysis.WindowRatioBounds','Universality.Percolation.WindowPairExpectation','Universality.Percolation.CriticalWindowAtCells','Universality.Percolation.CriticalWindowConnectivity','Universality.Percolation.AveragedConnectivityExponent','Universality.Examples.DiamondRadiusGeometry','Universality.Examples.DiamondOpenGeodesic','Universality.Examples.DiamondBranchDistance','Universality.Graph.GenerationTerminalEmbedding','Universality.Graph.AncestralStageRootLaw','Universality.Graph.AncestralStageJointLaw','Universality.Graph.CountableAgeMixture','Universality.Graph.UniformRootProbabilitySpace','Universality.Graph.FiniteBernoulliMeasure']
audits=['Universality.'+x for x in ['geometric_sum_from_one_bounds_above_one','geometric_sum_from_one_bounds_below_one','geometric_sum_log_rate','stopped_geometric_power_comparison','stopped_linear_log_comparison','Rule.Classical.reliability_exit_tendsto_atTop','Rule.Classical.root_moment_power_bounds_from_capped_comparison','Rule.Classical.root_moment_log_bounds_from_capped_comparison','Rule.Classical.supercritical_root_moment_power_bounds','Rule.Classical.supercritical_root_moment_log_bounds','Rule.Classical.subcritical_root_moment_power_bounds','Rule.Classical.subcritical_root_moment_log_bounds','window_ratio_bounds','FiniteNetwork.expectedConnectedWindowPairCount_le_boundary_second_moment','Rule.Classical.critical_window_bounds_at_cells','Rule.Classical.critical_window_connectivity_bounds','Rule.Classical.averaged_connectivity_logarithmic_exponent','Rule.Classical.averaged_connectivity_exponent','FiniteNetwork.substitute_terminal_distance_sum','diamond_generation_terminal_distance_sum','diamond_generation_layer','diamond_generation_diameter','FiniteNetwork.substituted_open_walk_length','FiniteNetwork.substitute_open_geodesic','diamond_generation_open_geodesic','FiniteNetwork.terminal_cut_distance','diamond_substitution_branch_distance','Rule.ancestralRootAtStage_measurePreserving','Rule.ancestralStageJoint_measurePreserving','Rule.ancestralStageClusterSize_probability','countableAgeMixture_probability','Rule.uniformRootFiniteClusterProbability_eq_mixture','Rule.uniformRootInfiniteClusterEvent_iff','Rule.uniformRootInfiniteClusterProbability_eq','finiteBernoulli_real_singleton','mappedFiniteUniformBernoulli_event']]
for prefix in ['Universality.FiniteNetwork.cellNetworkEmbedding_','Universality.Rule.generationCellEmbedding_']:
 audits += [prefix+x+'_iff' for x in ['source_eq_source','source_eq_target','target_eq_source','target_eq_target']]
for filename, items, prefix in [('Universality.lean',modules,'import '),('Audit.lean',audits,'#print axioms ')]:
 p=r/filename;t=p.read_text(encoding='utf-8-sig');current=set(t.splitlines());t=t.rstrip()+'\n';t+=''.join(prefix+x+'\n' for x in items if prefix+x not in current);p.write_text(t,encoding='utf-8')
(r/'scripts/section3_seventh_migration.json').write_text(json.dumps({'modules':modules,'audits':audits},indent=2)+'\n',encoding='utf-8')
print({'added_candidate_modules':len(modules),'candidate_audits':len(audits)})
